theme: minima
title: LG Writing
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A page for writing about writing.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: LAS3113

show_excerpts: true # set to false to remove excerpts on the homepage
